jhpy/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, filedown_views, main_views, notice_views

app_name='jhpy'

urlpatterns = [
    # main_views.py
    path('',main_views.notice, name='index'),
    
    # base_views.py
    path('qna/',
         base_views.qna, name='qna'),
    path('<int:question_id>/',
         base_views.detail, name='detail'),
    
    # notice_views.py
    path('notice/',
         notice_views.notice, name='notice'),
    path('notice/<int:notice_id>/',
         notice_views.notice_detail, name='notice_detail'),

    # question_views.py
    path('question/create/',
         question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/',
         question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/',
         question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/',
         answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',
         answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
         answer_views.answer_delete, name='answer_delete'),
    
    # filedownload
    path('fdownload/',
         filedown_views.download, name='fdownload'),
]

jhserver/urls.py
from django.contrib import admin
from django.urls import path, include
from jhpy.views import base_views, filedown_views, main_views
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('', main_views.notice, name='index'),
    path('admin/', admin.site.urls),
    path('jhpy/',include('jhpy.urls')),
    path('common/', include('common.urls')),
    path('download/', filedown_views.home, name='fdownload'),
    url(r'^download/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

jhpy/models.py
from django.db import models
from django.contrib.auth.models import User

class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    modify_date = models.DateTimeField(null=True, blank=True)
    create_date = models.DateTimeField()
    
    def __str__(self):
        return self.subject


class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    modify_date = models.DateTimeField(null=True, blank=True)
    create_date = models.DateTimeField()
    

class FilesAdmin(models.Model):
    adminupload=models.FileField(upload_to='media')
    title=models.CharField(max_length=50)
    
    def __str__(self):
        return self.title

    
class Notice(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    modify_date = models.DateTimeField(null=True, blank=True)
    create_date = models.DateTimeField()
    top_fixed = models.BooleanField(default=False)
    
    def __str__(self):
        return self.subject

jhpy/forms.py
from django import forms
from jhpy.models import Question, Answer, Notice


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용할 모델
        fields = ['subject', 'content']  # QuestionForm에서 사용할 Question 모델의 속성
        labels = {
            'subject': '제목',
            'content': '내용',
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }
        
        
class NoticeForm(forms.ModelForm):
    class Meta:
        model = Notice  # 사용할 모델
        fields = ['subject', 'content', 'top_fixed']  # QuestionForm에서 사용할 Question 모델의 속성
        labels = {
            'subject': '제목',
            'content': '내용',
        }

jhpy/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseNotAllowed
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import AnswerForm
from ..models import Question, Answer

@login_required(login_url='common:login')
def answer_create(request, question_id):
    question = Question.objects.get(id=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user  # author 속성에 로그인 계정 저장
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('jhpy:detail', question_id=question.id), answer.id))
    else:
        return HttpResponseNotAllowed('Only POST is possible.')
    context = {'question': question, 'form': form}
    return render(request, 'jhpy/question_detail.html', context)

@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('jhpy:detail', question_id=answer.question.id)
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('jhpy:detail', question_id=answer.question.id), answer.id))
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'jhpy/answer_form.html', context)

@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        answer.delete()
    return redirect('jhpy:detail', question_id=answer.question.id)

jhpy/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404

from ..models import Question

def qna(request):
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    question_list = Question.objects.order_by('-create_date')
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(answer__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct()
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj, 'page': page, 'kw': kw}
    return render(request, 'jhpy/question_list.html', context)

def detail(request, question_id):
    question = Question.objects.get(id=question_id)
    context = {'question': question}
    return render(request, 'jhpy/question_detail.html', context)

jhpy/views/filedown_views.py
from django.shortcuts import render
from ..models import FilesAdmin
from django.http import HttpResponse

def home(request):
    context={'file':FilesAdmin.objects.all()}
    return render(request, '/workspace/jhserver/templates/jhpy/filedown.html',context)

def download(request, path):
    file_path=os.path.join(settings.MEDIA_ROOT,path)
    if os.path.exists(file_path):
        with open(file_path,'rb')as fh:
            response=HttpResponse(fh.read(),content_type="application/adminupload")
            response['Content-Disposition']='inline;filename='+os.path.basename(file_path)
            return response
        
    raise Http404

jhpy/views/main_views.py
from django.shortcuts import render

'''def index(request):
	return render(request, 'jhpy/main.html')'''

from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404

from ..models import Notice

def notice(request):
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    notice_list = Notice.objects.order_by('-create_date')
    if kw:
        notice_list = notice_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(answer__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct()
    paginator = Paginator(notice_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'notice_list': page_obj, 'page': page, 'kw': kw}
    return render(request, 'jhpy/main.html', context)

def notice_detail(request, notice_id):
    notice = Notice.objects.get(id=notice_id)
    context = {'notice': notice}
    return render(request, 'jhpy/notice_detail.html', context)

jhpy/views/notice_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404

from ..models import Notice

def notice(request):
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    notice_list = Notice.objects.order_by('-create_date')
    if kw:
        notice_list = notice_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(answer__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct()
    paginator = Paginator(notice_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'notice_list': page_obj, 'page': page, 'kw': kw}
    return render(request, 'jhpy/main.html', context)

def notice_detail(request, notice_id):
    notice = Notice.objects.get(id=notice_id)
    context = {'notice': notice}
    return render(request, 'jhpy/notice_detail.html', context)

jhpy/views/question_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import QuestionForm
from ..models import Question

@login_required(login_url='common:login')
def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user  # author 속성에 로그인 계정 저장
            question.create_date = timezone.now()
            question.save()
            return redirect('jhpy:qna')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'jhpy/question_form.html', context)

@login_required(login_url='common:login')
def question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('jhpy:detail', question_id=question.id)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date = timezone.now()  # 수정일시 저장
            question.save()
            return redirect('jhpy:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'jhpy/question_form.html', context)

@login_required(login_url='common:login')
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('jhpy:detail', question_id=question.id)
    question.delete()
    return redirect('jhpy:qna')

templates/jhpy/answer_form.html
{% extends 'base.html' %}
{% block content %}
<!-- 답변 수정-->
<div class="container my-3">
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/jhpy/filedown.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<div class="container my-3">
    <table class="table" style="width:50%; margin:auto; margin-top:50px;">
        <thead>
        <tr class="text-center table-dark">
            <th>번호</th>
            <th style="width:50%">프로그램</th>
    		<th></th>
        </tr>
        </thead>
        <tbody>
        {% if file %}
        {% for post in file %}
        <tr class="text-center">
            <td>
                {{ forloop.counter }}
            </td>
            <td>{{post.title}}</td>
            <td>
                <a href="{{post.adminupload.url}}" download="{{post.adminupload.url}}">다운로드</a>
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="4">프로그램이 존재하지 않습니다. 관리자에게 문의하십시오.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
{% endblock %}

templates/jhpy/main.html
{% extends 'base.html' %}
{% load jhpy_filter %}
{% block content %}

<div class="contents">
    <div class="border">
        <img src="https://proxy.goorm.io/service/62dffc2d3611296cc504a1e0_dRjco00Lw8q7Tsw6djr.run.goorm.io/9080/file/load/maindesign.jpg?path=d29ya3NwYWNlJTJGamhzZXJ2ZXIlMkZzdGF0aWMlMkZtYWluZGVzaWduLmpwZw==&docker_id=dRjco00Lw8q7Tsw6djr&secure_session_id=bbR4M9ra1QQiPgSWUJAOgpxpLPJGta8n" style="position:absolute; width:100%; height:100%">
        <h1 style="position:absolute; color:white; margin:160px 50px 30px 50px">
            <span>JSecurityLab</span>
            <br>&ZeroWidthSpace;프로그램 개발 연구소
        </h1>
        <h1 style="position:absolute; color:white; margin:270px 0px 0px 50px; font-size:20px;">&ZeroWidthSpace;잊지못할 프로그램을 만나보세요!<h1>
    </div>
    <div class="border" style="position:absolute; width:800px; margin:100px 0px 0px 1050px;">
    <div class="title_height">
        <h2 style="color:white; margin-left:5px; margin-top:5px">
            공지사항
        </h2>
    </div>
    <div>
        <table class="table" style="width:95%; margin-left:20px; color:white">
        <thead>
        <tr class="text-center" style="background-color:purple;">
            <th>번호</th>
            <th style="width:30%">제목</th>
    		<th>글쓴이</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if notice_list %}
        {% for notice in notice_list %}
        <tr class="text-center">
            <td>
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ forloop.counter }}
            </td>
            <td class="text-start">
                <a href="{% url 'jhpy:notice_detail' notice.id %}">{{ notice.subject }}</a>
                {% if notice.answer_set.count > 0 %}
    			<span class="text-danger small mx-2">{{ notice.answer_set.count }}</span>
    			{% endif %}
            </td>
            <td>{{ notice.author.username }}</td>  <!-- 글쓴이 추가 -->
            <td>{{ notice.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="4">공지가 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    </div>
</div>
</div>
<form id="searchForm" method="get" action="{% url 'jhpy:notice' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('searchForm').submit();
});
</script>
{% endblock %}

templates/jhpy/notice_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <!-- message 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ notice.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ notice.content }}</div>
            <div class="d-flex justify-content-end">
                {% if notice.modify_date %}
            <div class="badge bg-light text-dark p-2 text-start mx-3">
                <div class="mb-2">{{ notice.author.username }}</div>
                <div>{{ notice.modify_date }}.수정됨</div>
            </div>
            	{% else %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ notice.author.username }}</div>
                    <div>{{ notice.create_date }}</div>
                </div>
                {% endif %}
            </div>
            <div class="my-3">
        	</div>
        </div>
    </div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

templates/jhpy/question_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <!-- message 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                {% if question.modify_date %}
            <div class="badge bg-light text-dark p-2 text-start mx-3">
                <div class="mb-2">{{ question.author.username }}</div>
                <div>{{ question.modify_date }}.수정됨</div>
            </div>
            	{% else %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ question.author.username }}</div>
                    <div>{{ question.create_date }}</div>
                </div>
                {% endif %}
            </div>
            <div class="my-3">
            {% if request.user == question.author %}
            <a href="{% url 'jhpy:question_modify' question.id  %}" 
               class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
       data-uri="{% url 'jhpy:question_delete' question.id  %}">삭제</a>
            {% endif %}
        	</div>
        </div>
    </div>
    <!-- 답변 -->
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <a id="answer_{{ answer.id }}"></a>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                {% if answer.modify_date %}
            <div class="badge bg-light text-dark p-2 text-start mx-3">
                <div class="mb-2">{{ answer.author.username }}</div>
                <div>{{ answer.modify_date }}.수정됨</div>
            </div>
            	{% else %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ answer.author.username }}</div>
                    <div>{{ answer.create_date }}</div>
                </div>
                {% endif %}
            </div>
            <div class="my-3">
            {% if request.user == answer.author %}
            <a href="{% url 'jhpy:answer_modify' answer.id  %}" 
               class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary "
               data-uri="{% url 'jhpy:answer_delete' answer.id  %}">삭제</a>
            {% endif %}
        	</div>
        </div>
    </div>
    {% endfor %}
    <!-- 답변 등록 -->
    <form action="{% url 'jhpy:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
              name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

templates/jhpy/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="subject" class="form-label">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/jhpy/question_list.html
{% extends 'base.html' %}
{% load jhpy_filter %}
{% block content %}

<div class="container my-3">
    <div class="row my-3">
        <div class="col-6">
            <a href="{% url 'jhpy:question_create' %}" class="btn btn-primary">질문 등록하기</a>
        </div>
        <div class="col-6">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
        <tr class="text-center" style="background-color: aquamarine;">
            <th>번호</th>
            <th style="width:50%">제목</th>
    		<th>글쓴이</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr class="text-center">
            <td>
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td class="text-start">
                <a href="{% url 'jhpy:detail' question.id %}">{{ question.subject }}</a>
                {% if question.answer_set.count > 0 %}
    			<span class="text-danger small mx-2">{{ question.answer_set.count }}</span>
    			{% endif %}
            </td>
            <td>{{ question.author.username }}</td>  <!-- 글쓴이 추가 -->
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="4">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.previous_page_number }}"
           href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
        {% if page_number == question_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" data-page="{{ page_number }}"
           href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" data-page="{{ page_number }}"
           href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% endif %}
		{% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.next_page_number }}"
           href="javascript:void(0)">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
</div>
<form id="searchForm" method="get" action="{% url 'jhpy:qna' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('searchForm').submit();
});
</script>
{% endblock %}